/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, copyDefault, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && (copyDefault || key !== "default"))
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toCommonJS = /* @__PURE__ */ ((cache) => {
  return (module2, temp) => {
    return cache && cache.get(module2) || (temp = __reExport(__markAsModule({}), module2, 1), cache && cache.set(module2, temp), temp);
  };
})(typeof WeakMap !== "undefined" ? /* @__PURE__ */ new WeakMap() : 0);
var __publicField = (obj, key, value) => {
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
  return value;
};

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => WikicodianPlugin
});
var import_obsidian = require("obsidian");
var VIEW_TYPE_WIKICODIAN = "wikicodian-chat-view";
var DEFAULT_SETTINGS = {
  serverUrl: "http://127.0.0.1:8000",
  agentSearchLimit: 8,
  boostTerms: "\u7ED3\u7B97, \u6807\u51C6, \u7EAA\u8981, 2024, 66\u53F7",
  wikiEnabled: false,
  reportTemplate: "business_audit.md"
};
var SLASH_COMMANDS = [
  { name: "/help", desc: "\u{1F4E1} \u6B63\u5728\u4ECE\u540E\u7AEF\u540C\u6B65\u6307\u4EE4\u96C6..." }
];
var WikicodianView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    __publicField(this, "settings");
    __publicField(this, "plugin");
    __publicField(this, "messages", []);
    __publicField(this, "suggestIndex", -1);
    __publicField(this, "filteredCommands", []);
    __publicField(this, "chatMode", "plan");
    __publicField(this, "messageContainer");
    __publicField(this, "inputEl");
    __publicField(this, "inputHistory", []);
    __publicField(this, "historyIndex", -1);
    __publicField(this, "suggestContainer");
    __publicField(this, "taskContainer");
    __publicField(this, "fileTagEl");
    __publicField(this, "wikiStatusEl");
    __publicField(this, "currentActiveFile", null);
    __publicField(this, "updateActiveFileUI");
    __publicField(this, "allSeenTasks", []);
    __publicField(this, "completedTasks", /* @__PURE__ */ new Set());
    __publicField(this, "modeSelect");
    this.plugin = plugin;
    this.settings = plugin.settings;
  }
  getViewType() {
    return VIEW_TYPE_WIKICODIAN;
  }
  getDisplayText() {
    return "Wikicodian Chat";
  }
  getIcon() {
    return "bot";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("wikicodian-chat-container");
    try {
      const cmdRes = await (0, import_obsidian.requestUrl)({ url: `${this.settings.serverUrl}/v1/commands` });
      if (cmdRes.json && Array.isArray(cmdRes.json)) {
        SLASH_COMMANDS = cmdRes.json;
      }
    } catch (e) {
      console.error("Failed to load commands from backend:", e);
    }
    const statusBar = container.createEl("div", { cls: "wikicodian-sync-bar" });
    const statusInfo = statusBar.createEl("div");
    statusInfo.createEl("span", { cls: "wikicodian-status-dot wikicodian-status-online" });
    statusInfo.createSpan({ text: "WikiCoder Online" });
    const syncBtn = statusBar.createEl("button", { text: "\u540C\u6B65\u4E13\u5BB6\u56FE\u8C31", cls: "mod-cta" });
    syncBtn.onclick = () => this.executeSlashCommand("/sync");
    this.taskContainer = container.createEl("div", { cls: "wikicodian-task-panel" });
    this.taskContainer.style.display = "none";
    this.messageContainer = container.createEl("div", { cls: "wikicodian-chat-messages markdown-preview-view" });
    this.suggestContainer = container.createEl("div", { cls: "wikicodian-suggest-container" });
    this.suggestContainer.style.display = "none";
    const inputWrapper = container.createEl("div", { cls: "wikicodian-input-wrapper" });
    this.inputEl = inputWrapper.createEl("textarea", {
      cls: "wikicodian-chat-input",
      attr: { placeholder: "What's new, \u8001\u677F?" }
    });
    const controlBar = inputWrapper.createEl("div", { cls: "wikicodian-control-bar" });
    const controlLeft = controlBar.createEl("div", { cls: "wikicodian-control-left" });
    this.modeSelect = controlLeft.createEl("select", { cls: "wikicodian-mode-select" });
    const modes = [{ id: "plan", label: "\u{1F4DD} Plan" }, { id: "build", label: "\u{1F680} Build" }];
    modes.forEach((m) => {
      const opt = this.modeSelect.createEl("option", { value: m.id, text: m.label });
      if (this.chatMode === m.id)
        opt.selected = true;
    });
    this.modeSelect.onchange = (e) => {
      this.chatMode = e.target.value;
    };
    this.wikiStatusEl = controlLeft.createEl("div", { cls: "wikicodian-wiki-status" });
    this.updateWikiUI();
    this.wikiStatusEl.onclick = async () => {
      this.settings.wikiEnabled = !this.settings.wikiEnabled;
      await this.plugin.saveSettings();
      this.updateWikiUI();
      new import_obsidian.Notice(this.settings.wikiEnabled ? "\u{1F4DA} \u5168\u5C40 Wiki \u589E\u5F3A\u5DF2\u5F00\u542F" : "\u{1F4DA} \u5168\u5C40 Wiki \u589E\u5F3A\u5DF2\u5173\u95ED");
    };
    this.fileTagEl = controlLeft.createEl("div", { cls: "wikicodian-file-tag" });
    this.updateActiveFileUI = () => {
      const activeFile = this.app.workspace.getActiveFile();
      if (activeFile) {
        this.currentActiveFile = activeFile;
        this.fileTagEl.empty();
        this.fileTagEl.createEl("span", { text: "\u{1F4C4}", cls: "wikicodian-file-icon" });
        this.fileTagEl.createEl("span", { text: activeFile.basename });
        const closeBtn = this.fileTagEl.createEl("span", { text: "\u2715", cls: "wikicodian-file-close" });
        closeBtn.onclick = (e) => {
          e.stopPropagation();
          this.currentActiveFile = null;
          this.fileTagEl.style.display = "none";
        };
        this.fileTagEl.style.display = "flex";
      } else {
        this.currentActiveFile = null;
        this.fileTagEl.style.display = "none";
      }
    };
    this.updateActiveFileUI();
    this.registerEvent(this.app.workspace.on("file-open", this.updateActiveFileUI));
    const controlRight = controlBar.createEl("div", { cls: "wikicodian-control-right" });
    const interruptBtn = controlRight.createEl("button", { text: "\u23F9 \u4E2D\u65AD", cls: "wikicodian-yolo-btn" });
    interruptBtn.style.display = "none";
    let currentAbortController = null;
    interruptBtn.onclick = () => {
      if (currentAbortController) {
        currentAbortController.abort();
        currentAbortController = null;
        new import_obsidian.Notice("\u23F9 \u4EFB\u52A1\u5DF2\u5F3A\u884C\u4E2D\u6B62 (\u534F\u4F5C\u5F0F)");
      }
    };
    const handleSend = async () => {
      var _a, _b;
      let query = this.inputEl.value.trim();
      if (!query)
        return;
      if (this.settings.wikiEnabled && !query.toLowerCase().includes("@wikiagent")) {
        query = `@wikiagent ${query}`;
      }
      if (query.startsWith("/")) {
        this.executeSlashCommand(query);
        this.inputEl.value = "";
        return;
      }
      if (!this.inputHistory.includes(query)) {
        this.inputHistory.push(query);
      }
      this.historyIndex = this.inputHistory.length;
      this.inputEl.value = "";
      const attachedPath = this.currentActiveFile && this.app.vault.adapter instanceof import_obsidian.FileSystemAdapter ? this.app.vault.adapter.getFullPath(this.currentActiveFile.path) : "";
      let displayQuery = query;
      let backendQuery = query;
      if (attachedPath) {
        displayQuery = `\u{1F4CE} **\u9644\u4EF6**: \`${(_a = this.currentActiveFile) == null ? void 0 : _a.basename}\`
${query}`;
        backendQuery = `[\u9644\u8A00\uFF1A\u5F53\u524D\u6211\u5728\u5C4F\u5E55\u4E0A\u6B63\u5728\u6D4F\u89C8\u548C\u7F16\u8F91\u8BE5\u6587\u4EF6\uFF1A${attachedPath}]

${query}`;
      }
      await this.appendMessage("user", displayQuery);
      this.messages.push({ q: backendQuery, a: "" });
      const currentMsgIndex = this.messages.length - 1;
      const statusEl = this.messageContainer.createEl("div", { cls: "wikicodian-message wikicodian-status-msg" });
      statusEl.setText(`\u{1F9E0} \u6B63\u5728\u6DF1\u5EA6\u62C6\u89E3\u6307\u4EE4...`);
      interruptBtn.style.display = "block";
      currentAbortController = new AbortController();
      try {
        const vaultPath = this.app.vault.adapter.basePath || "";
        const response = await fetch(`${this.settings.serverUrl}/v1/chat`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            query: backendQuery,
            mode: this.chatMode,
            history: this.messages.slice(-5),
            cwd: vaultPath,
            agent_search_limit: this.settings.agentSearchLimit,
            rag_filename_boost_terms: this.settings.boostTerms.split(",").map((t) => t.trim()).filter((t) => t),
            report_template: this.settings.reportTemplate
          }),
          signal: currentAbortController.signal
        });
        const reader = (_b = response.body) == null ? void 0 : _b.getReader();
        const decoder = new TextDecoder();
        let hasStarted = false;
        let botMsgEl = null;
        let botStatusEl = null;
        let botContentEl = null;
        let fullContent = "";
        const thoughts = [];
        if (reader) {
          while (true) {
            const { done, value } = await reader.read();
            if (done)
              break;
            const chunk = decoder.decode(value);
            const lines = chunk.split("\n");
            for (const line of lines) {
              if (line.startsWith("data: ")) {
                const dataStr = line.slice(6).trim();
                if (dataStr === "[DONE]")
                  continue;
                try {
                  const json = JSON.parse(dataStr);
                  if (!hasStarted) {
                    hasStarted = true;
                    statusEl.remove();
                    botMsgEl = await this.appendMessage("bot", "");
                    botStatusEl = botMsgEl.createEl("div", { cls: "wikicodian-thought-bubble" });
                    botContentEl = botMsgEl.createEl("div", { cls: "markdown-rendered" });
                  }
                  if (json.status) {
                    const isTimer = json.status.includes("(\u5DF2\u8017\u65F6");
                    const lastThought = thoughts.length > 0 ? thoughts[thoughts.length - 1] : null;
                    const lastIsTimer = lastThought && lastThought.includes("(\u5DF2\u8017\u65F6");
                    if (isTimer && lastIsTimer) {
                      thoughts[thoughts.length - 1] = json.status;
                    } else if (lastThought !== json.status) {
                      thoughts.push(json.status);
                    }
                    botStatusEl.empty();
                    thoughts.forEach((t, i) => {
                      botStatusEl.createEl("div", {
                        text: `${i + 1}. ${t}`,
                        cls: "wikicodian-thought-step"
                      });
                    });
                  }
                  if (json.output) {
                    if (botStatusEl && botStatusEl.style.display !== "none") {
                      botStatusEl.style.display = "none";
                    }
                    fullContent += json.output;
                    this.messages[currentMsgIndex].a = fullContent;
                    if (botContentEl) {
                      botContentEl.empty();
                      import_obsidian.MarkdownRenderer.renderMarkdown(fullContent, botContentEl, "", this);
                    }
                    this.messageContainer.scrollTo(0, this.messageContainer.scrollHeight);
                  }
                } catch (e) {
                }
              }
            }
          }
        }
      } catch (e) {
        if (statusEl)
          statusEl.remove();
        if (e.name === "AbortError")
          await this.appendMessage("bot", `\u26A0\uFE0F **\u4EFB\u52A1\u5DF2\u5F3A\u5236\u4E2D\u6B62\u3002** \u540E\u7AEF\u5DF2\u5B89\u5168\u56DE\u6536\u8D44\u6E90\u3002`);
        else
          await this.appendMessage("bot", `### \u274C \u8FDE\u63A5\u5931\u8D25
\u8BF7\u68C0\u67E5\u540E\u7AEF \`serve\`\u3002`);
      } finally {
        interruptBtn.style.display = "none";
        currentAbortController = null;
      }
    };
    this.inputEl.oninput = () => {
      const val = this.inputEl.value;
      if (val.startsWith("/")) {
        const search = val.slice(1).toLowerCase();
        this.filteredCommands = SLASH_COMMANDS.filter((c) => c.name.toLowerCase().includes(search) || c.desc && c.desc.toLowerCase().includes(search));
        if (this.filteredCommands.length > 0) {
          this.suggestIndex = 0;
          this.renderSuggest();
        } else {
          this.suggestContainer.style.display = "none";
        }
      } else {
        this.suggestContainer.style.display = "none";
      }
    };
    this.inputEl.onkeydown = (e) => {
      if (this.suggestContainer.style.display !== "none" && this.filteredCommands.length > 0) {
        if (e.key === "ArrowDown") {
          e.preventDefault();
          this.suggestIndex = (this.suggestIndex + 1) % this.filteredCommands.length;
          this.renderSuggest();
        } else if (e.key === "ArrowUp") {
          e.preventDefault();
          this.suggestIndex = (this.suggestIndex - 1 + this.filteredCommands.length) % this.filteredCommands.length;
          this.renderSuggest();
        } else if (e.key === "Enter" || e.key === "Tab") {
          e.preventDefault();
          const cmd = this.filteredCommands[this.suggestIndex].name;
          this.inputEl.value = cmd + " ";
          this.suggestContainer.style.display = "none";
          this.inputEl.focus();
        } else if (e.key === "Escape") {
          this.suggestContainer.style.display = "none";
        }
      } else {
        if (e.key === "Enter" && !e.shiftKey) {
          e.preventDefault();
          handleSend();
        } else if (e.key === "ArrowUp") {
          if (this.historyIndex > 0) {
            e.preventDefault();
            this.historyIndex--;
            this.inputEl.value = this.inputHistory[this.historyIndex];
          }
        } else if (e.key === "ArrowDown") {
          if (this.historyIndex < this.inputHistory.length - 1) {
            e.preventDefault();
            this.historyIndex++;
            this.inputEl.value = this.inputHistory[this.historyIndex];
          } else if (this.historyIndex === this.inputHistory.length - 1) {
            e.preventDefault();
            this.historyIndex++;
            this.inputEl.value = "";
          }
        }
      }
    };
  }
  renderSuggest() {
    this.suggestContainer.empty();
    this.suggestContainer.style.display = "block";
    this.filteredCommands.forEach((cmd, i) => {
      const item = this.suggestContainer.createEl("div", { cls: "wikicodian-suggest-item" });
      if (i === this.suggestIndex) {
        item.addClass("is-selected");
        setTimeout(() => item.scrollIntoView({ block: "nearest", behavior: "smooth" }), 50);
      }
      item.createSpan({ text: cmd.name, cls: "wikicodian-suggest-name" });
      item.createSpan({ text: cmd.desc, cls: "wikicodian-suggest-desc" });
      item.onclick = () => {
        this.inputEl.value = cmd.name + " ";
        this.suggestContainer.style.display = "none";
        this.inputEl.focus();
      };
    });
  }
  updateWikiUI() {
    this.wikiStatusEl.empty();
    const dot = this.wikiStatusEl.createEl("span", { cls: "wikicodian-status-dot" });
    dot.style.background = this.settings.wikiEnabled ? "#a371f7" : "#888";
    this.wikiStatusEl.createSpan({ text: this.settings.wikiEnabled ? "\u4E13\u5BB6\u6A21\u578B: ON" : "\u4E13\u5BB6\u6A21\u578B: OFF" });
  }
  async appendMessage(role, text) {
    const msgEl = this.messageContainer.createEl("div", { cls: `wikicodian-message wikicodian-message-${role}` });
    if (role === "user") {
      msgEl.setText(text);
    } else {
      msgEl.addClass("markdown-rendered");
      await import_obsidian.MarkdownRenderer.renderMarkdown(text, msgEl, "", this);
    }
    this.messageContainer.scrollTo(0, this.messageContainer.scrollHeight);
    return msgEl;
  }
  async executeSlashCommand(cmd) {
    await this.appendMessage("user", cmd);
    try {
      const res = await (0, import_obsidian.requestUrl)({
        url: `${this.settings.serverUrl}/v1/exec`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          command: cmd,
          history: this.messages.slice(-10)
        })
      });
      const data = res.json;
      await this.appendMessage("bot", data.output || "\u6267\u884C\u6210\u529F");
      if (data.history && Array.isArray(data.history)) {
        this.messages = data.history.map((h) => ({ q: h[0], a: h[1] }));
        this.messageContainer.empty();
        for (const h of data.history) {
          await this.appendMessage("user", h[0]);
          await this.appendMessage("bot", h[1]);
        }
      }
      if (data.mode) {
        this.chatMode = data.mode;
        this.modeSelect.value = data.mode;
      }
      if (cmd.startsWith("/reset")) {
        this.messages = [];
        this.messageContainer.empty();
        await this.appendMessage("bot", "\u{1F9F9} \u4F1A\u8BDD\u5DF2\u91CD\u7F6E\u3002");
      }
    } catch (e) {
      await this.appendMessage("bot", "### \u274C \u6267\u884C\u5931\u8D25\n\u8BF7\u68C0\u67E5\u540E\u7AEF\u8FDE\u63A5\u6216\u6307\u4EE4\u8BED\u6CD5\u3002");
    }
  }
};
var WikicodianPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    __publicField(this, "settings");
  }
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_WIKICODIAN, (leaf) => new WikicodianView(leaf, this));
    this.addRibbonIcon("bot", "Wikicodian Chat", () => this.activateView());
    this.addSettingTab(new WikicodianSettingTab(this.app, this));
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_WIKICODIAN)[0];
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        leaf = rightLeaf;
        await leaf.setViewState({ type: VIEW_TYPE_WIKICODIAN, active: true });
      }
    }
    if (leaf)
      workspace.revealLeaf(leaf);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var WikicodianSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    __publicField(this, "plugin");
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "WikiCoder \u63D2\u4EF6\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("Backend URL").addText((text) => text.setValue(this.plugin.settings.serverUrl).onChange(async (v) => {
      this.plugin.settings.serverUrl = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u68C0\u7D22\u8D44\u6599\u6761\u6570").setDesc("WikiAgent \u6BCF\u6B21\u5BF9\u8BDD\u53C2\u8003\u7684\u8D44\u6599\u6DF1\u5EA6 (\u9ED8\u8BA4 8)").addSlider((slider) => slider.setLimits(1, 20, 1).setValue(this.plugin.settings.agentSearchLimit).onChange(async (v) => {
      this.plugin.settings.agentSearchLimit = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u5F3A\u5236\u52A0\u6743\u8BCD\u5E93").setDesc("\u4EE5\u9017\u53F7\u5206\u9694\uFF0C\u547D\u4E2D\u8FD9\u4E9B\u8BCD\u7684\u6587\u4EF6\u5C06\u4F18\u5148\u5C55\u793A").addText((text) => text.setValue(this.plugin.settings.boostTerms).onChange(async (v) => {
      this.plugin.settings.boostTerms = v;
      await this.plugin.saveSettings();
    }));
    const templateSetting = new import_obsidian.Setting(containerEl).setName("\u62A5\u544A\u5408\u6210\u6A21\u677F").setDesc("\u6307\u5B9A AI \u751F\u6210\u6700\u7EC8\u62A5\u544A\u65F6\u4F7F\u7528\u7684\u6A21\u677F (\u81EA\u52A8\u4ECE\u540E\u7AEF\u540C\u6B65)");
    templateSetting.addDropdown(async (dropdown) => {
      dropdown.addOption(this.plugin.settings.reportTemplate, "\u{1F504} \u6B63\u5728\u540C\u6B65\u6A21\u677F...");
      try {
        const res = await (0, import_obsidian.requestUrl)({
          url: `${this.plugin.settings.serverUrl}/v1/templates`,
          method: "GET"
        });
        if (res.json && res.json.templates) {
          const selectEl = dropdown.selectEl;
          selectEl.empty();
          res.json.templates.forEach((t) => {
            dropdown.addOption(t.id, t.name);
          });
          if (!this.plugin.settings.reportTemplate || this.plugin.settings.reportTemplate === "business_audit.md") {
            this.plugin.settings.reportTemplate = res.json.default;
          }
          dropdown.setValue(this.plugin.settings.reportTemplate);
        }
      } catch (e) {
        console.error("Failed to sync templates:", e);
        const selectEl = dropdown.selectEl;
        selectEl.empty();
        dropdown.addOption("business_audit.md", "Business Audit (Fallback)");
        dropdown.setValue("business_audit.md");
      }
      dropdown.onChange(async (v) => {
        this.plugin.settings.reportTemplate = v;
        await this.plugin.saveSettings();
        new import_obsidian.Notice(`\u{1F4CB} \u5DF2\u5207\u6362\u6A21\u677F\u4E3A: ${v}`);
      });
    });
  }
};
module.exports = __toCommonJS(main_exports);
